# Generated by Django 4.2.3 on 2023-11-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('started_at', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
