# Generated by Django 4.2.3 on 2023-11-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_employeemodel_delete_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeemodel',
            options={'ordering': ('started_at',)},
        ),
    ]
